language: node_js
node_js:
  - "6"
  - "8"
  - "node"
env:
  global:
    - REPO_OWNER=vokal
    - REPO_NAME=cvr
install:
  - npm install -g istanbul
  - npm install
script:
  - chmod +x run-build.sh
  - ./run-build.sh
